// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyWorkTask.Model.Context;

#nullable disable

namespace SkyWorkTask.Migrations
{
    [DbContext(typeof(PengajuanKreditContext))]
    [Migration("20251205055212_CreatePengajuanKredit")]
    partial class CreatePengajuanKredit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyWorkTask.Model.PengajuanKredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Angsuran")
                        .HasColumnType("integer");

                    b.Property<decimal>("Bunga")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plafon")
                        .HasColumnType("integer");

                    b.Property<int>("Tenor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Plafon")
                        .HasDatabaseName("idx_plafon");

                    b.HasIndex("Tenor")
                        .HasDatabaseName("idx_Tenor");

                    b.ToTable("PengajuanKredits");
                });
#pragma warning restore 612, 618
        }
    }
}
